let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? 'شخص عادي 👦🏻'
      : ((user.level >= 3) && (user.level <= 6)) ? 'شونين🥷'
      : ((user.level >= 7) && (user.level <= 8)) ? 'قرصان🏴‍☠️'
      : ((user.level >= 9) && (user.level <= 10)) ? ' جندي بحرية 👮🏼‍♀️ '
      : ((user.level >= 11) && (user.level <= 12)) ? 'صائد قراصنة 💀'
      : ((user.level >= 13) && (user.level <= 14)) ? 'قبطان 👨🏻‍✈️'
      : ((user.level >= 15) && (user.level <= 16)) ? 'شونين⚔️'
      : ((user.level >= 17) && (user.level <= 18)) ? 'ساحر🧙‍♂️'
      : ((user.level >= 19) && (user.level <= 20)) ? 'نينجا🕵️‍♂️'
      : ((user.level >= 21) && (user.level <= 22)) ? 'هيلر⛑️'
      : ((user.level >= 23) && (user.level <= 24)) ? 'هوكاغي 🎗'
      : ((user.level >= 25) && (user.level <= 26)) ? 'قائد الأسطول ☠️'
      : ((user.level >= 27) && (user.level <= 28)) ? ' ادميرال 🖤'
      : ((user.level >= 29) && (user.level <= 30)) ? 'ساموراي 🗡️'
      : ((user.level >= 31) && (user.level <= 32)) ? 'قاتل شياطين 👌🏻'
      : ((user.level >= 33) && (user.level <= 34)) ? ' هاشيرا 🔥'
      : ((user.level >= 35) && (user.level <= 36)) ? 'ملك شياطين⚕️'
      : ((user.level >= 37) && (user.level <= 38)) ? 'قمر ادنى 👿'
      : ((user.level >= 39) && (user.level <= 40)) ? 'قمر أعلى 👹'
      : ((user.level >= 41) && (user.level <= 42)) ? 'ساحر هايدرو 🏹'
      : ((user.level >= 43) && (user.level <= 44)) ? 'مساعد حاكم الدمار 🐱'
      : ((user.level >= 45) && (user.level <= 46)) ? 'حاكم الدمار👺'
      : ((user.level >= 47) && (user.level <= 48)) ? 'أركون 🔮'
      : ((user.level >= 49) && (user.level <= 50)) ? 'حامل فيجين 👹'
      : ((user.level >= 51) && (user.level <= 52)) ? 'فاتوي 👑'
      : ((user.level >= 53) && (user.level <= 54)) ? 'سايان 🔥'
      : ((user.level >= 55) && (user.level <= 56)) ? 'شينيغامي 💀'
      : ((user.level >= 57) && (user.level <= 58)) ? 'تنين🔥'
      : ((user.level >= 59) && (user.level <= 60)) ? 'دارك فيجين💥'
      : ((user.level >= 61) && (user.level <= 62)) ? 'جوي بوي🦹‍♂️'
      : ((user.level >= 63) && (user.level <= 64)) ? 'بطل خارق⚡'
      : ((user.level >= 65) && (user.level <= 66)) ? 'الافاتار🌊'
      : ((user.level >= 67) && (user.level <= 68)) ? 'زينوس 🐉'
      : ((user.level >= 69) && (user.level <= 70)) ? 'ملك التنانين 👑'
      : ((user.level >= 71) && (user.level <= 72)) ? 'تشيبوكاي 🪝'      
      : ((user.level >= 73) && (user.level <= 74)) ? 'نائب يونكو 💂🏼'
      : ((user.level >= 75) && (user.level <= 76)) ? 'يونكو 🧛🏻'
      : ((user.level >= 77) && (user.level <= 78)) ? 'عملاق الموسس🐒'
      : ((user.level >= 79) && (user.level <= 80)) ? 'نائب ملك قراصنة🏴‍☠️'
      : ((user.level >= 81) && (user.level <= 82)) ? 'ملك قراصنة👒'
      : ((user.level >= 83) && (user.level <= 84)) ? 'Esmeralda I'
      : ((user.level >= 85) && (user.level <= 86)) ? 'Titan III'
      : ((user.level >= 87) && (user.level <= 88)) ? 'Titan II'
      : ((user.level >= 89) && (user.level <= 90)) ? 'Titan I'
            : ((user.level >= 89) && (user.level <= 967)) ? 'الإمبراطور السحري🔥 الأعظم🔥'
      : 'الأمبراطور السحري الأعظم'

    user.role = role
    return true
}

export default handler
